services:
  - type: web
    name: shrinklink-app
    env: node
    plan: free
    buildCommand: npm install && cd FRONTEND && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: your_super_secret_jwt_key_here_make_it_long_and_random_123456789
      - key: PORT
        value: 10000
      - key: APP_URL
        sync: false
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/*
      - type: rewrite
        source: /*
        destination: /index.html
